### ISSUE TITLE
How to customize the popup information.

### ISSUE THREAD

**Issue by firmandev** [ccnnde/react-native-simple-openvpn#10]
Your code is amazing and easy to use, but there is lack customization in pop up information when VPN got connected, can you tell me which part of code that responsible for that so i can try to modify. (i`m not familiar with JAVA).

Thanks.

**Comment by ccnnde** [comment]
Thank you for your praise. What does "pop up information" mean? 

The code of the OpenVPN core library is not written by me, I think I may not be able to help you.

**Comment by ccnnde** [comment]
Thank you for your praise. What does "pop up information" mean? 

The code of the OpenVPN core library is not written by me, I think I may not be able to help you.

**Comment by firmandev** [comment]
> Thank you for your praise. What does "pop up information" mean?
> 
> The code of the OpenVPN core library is not written by me, I think I may not be able to help you.
![WhatsApp Image 2022-03-09 at 21 05 42](https://user-images.githubusercontent.com/21354151/157457505-ed212c97-f4e5-4899-8b20-a60ce8c26e27.jpeg)

**Comment by ccnnde** [comment]
okay

**Comment by burak1231** [comment]
@firmandev Can you tell me which file? :)

**Comment by firmandev** [comment]
@burak1231 haha tomorrow i will check
