### ISSUE TITLE
Get current VPN state

### ISSUE THREAD

**Issue by Ehsan0Hejazi** [ccnnde/react-native-simple-openvpn#11]
**Is your feature request related to a problem? If so, Please describe.**

**Describe the solutions you came up with**

**Additional context**

Is there any way to get current state whenever we request ?
I want to be able to understand the current state after closing and opening the app

**Comment by firmandev** [comment]
lol, i got same problem too. I have different solution, by using another modules for checking current external IP, if the external IP match your vpn server then it is connected :)

**Comment by Ehsan0Hejazi** [comment]
Interesting solution and thanks for responding,
could you please share with me more details so I can come up with this problem as well 
thanks

**Comment by firmandev** [comment]
@Ehsan0Hejazi  first of all, you need to install this https://www.npmjs.com/package/react-native-public-ip 
then you just need to get the public ip then match it with your open vpn server ip, if it match then your vpn is connected.

**Comment by brobin002** [comment]
Hi! Add this to  RNSimpleOpenvpnModule.java :)

/**
   * Get service status
   * @return
   */
  @ReactMethod
  public void getIsVPNActive(Callback callback) {
    callback.invoke(VpnStatus.isVPNActive());
  }

**Comment by ccnnde** [comment]
Supported
