### ISSUE TITLE
Customize notification

### ISSUE THREAD

**Issue by firmandev** [ccnnde/react-native-simple-openvpn#12]
im not familiar with java, is there any way to make the push notification to redirect to the apps if clicked ?
and adding some connection bandwith information in the push notification.

thanks.

**Comment by ccnnde** [comment]
Actually , I am not familiar with Java too. You can take a look at [Cake-VPN](https://github.com/ashraf789/Cake-VPN) and [ics-openvpn](https://github.com/schwabe/ics-openvpn).

**Comment by ccnnde** [comment]
I just used the latest built apk of ics-openvpn and it has all the functions you mentioned. So if I update the core library, these functions should also exist.

**Comment by firmandev** [comment]
please update it sir, because i need it.

**Comment by ccnnde** [comment]
Supported

**Comment by firmandev** [comment]
well the push notification is not redirecting to apps
i have tried the latest one.
