### ISSUE TITLE
Cannot redirect Push notification when clicked to the APP

### ISSUE THREAD

**Issue by firmandev** [ccnnde/react-native-simple-openvpn#18]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Environment:**
 in every environment

** My Guess **

 PendingIntent getLogPendingIntent() {
        if (mContentIntent == null) {
            mContentIntent = new Intent(getBaseContext(), Intent.class);
        }
        //intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
        return PendingIntent.getActivity(this, 0, mContentIntent, PendingIntent.FLAG_MUTABLE);
    }
this is the problem, but i dunno what to change the Intent.class

**Comment by ccnnde** [comment]
This line of code is used to open the MainActivity of the App.

https://github.com/ccnnde/react-native-simple-openvpn/blob/e73019cd577bdd6e1cd9d8da9860286f602fb00c/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L453

Please check your `AndroidManifest.xml`

https://github.com/ccnnde/react-native-simple-openvpn/blob/e73019cd577bdd6e1cd9d8da9860286f602fb00c/example/android/app/src/main/AndroidManifest.xml#L14

**Comment by ccnnde** [comment]
You should use v2.0.0, or modify the old code yourself

**Comment by firmandev** [comment]
> You should use v2.0.0, or modify the old code yourself

i have used your v2.0.0 still not changing, i will try use it again

**Comment by firmandev** [comment]
ohh i think i understand why it didnt work in your v.2.0.0, i have used it anyway but not working it is because of the name of my AndroidManifest, i have reconfig again, but still not working, it is cause you call the AndroidManifext in example folder ?
react folder is not in node modules, how to reconfig that ?

**Comment by firmandev** [comment]
this is how to reproduce, create new react native then install it using npm, it will behave different.

**Comment by firmandev** [comment]
i even concat it manual like this still not working  

`intent.setComponent(new ComponentName(this, "myPackagesName.MainApplication"));`

**Comment by firmandev** [comment]
Okay this is my conclusion, thanks for your inspiration

THIS IS WORKING, I HAVE TESTED IT.

`PendingIntent getGraphPendingIntent() {

        String packageName = getApplicationContext().getPackageName();
        if (mContentIntent == null) {
            mContentIntent = getPackageManager().getLaunchIntentForPackage(packageName);
        }
        //intent.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
        return PendingIntent.getActivity(this, 0, mContentIntent, PendingIntent.FLAG_MUTABLE);
    }`
