### ISSUE TITLE
connecting but can't connected 

### ISSUE THREAD

**Issue by nthiendev** [ccnnde/react-native-simple-openvpn#20]
**Bug description:**

**To Reproduce:**
<img width="699" alt="Screen Shot 2022-04-22 at 17 20 26" src="https://user-images.githubusercontent.com/87758174/164692360-18c845c6-a284-44a2-a111-1f569f1c0187.png">

**Expected behavior:**

**Screenshots/Videos:**
<img width="945" alt="Screen Shot 2022-04-22 at 17 15 40" src="https://user-images.githubusercontent.com/87758174/164693371-daa99bb8-7a0e-4dd5-971f-04a5a718c95e.png">

**Environment:**
 - OS:
 - OS version: 
 - react-native version: 0.68.1
 - react-native-simple-openvpn version: "^2.0.0"

**Comment by ccnnde** [comment]
Please configure the `compatMode` and `useLegacyProvider` options correctly

**Comment by nthiendev** [comment]
> Please configure the `compatMode` and `useLegacyProvider` options correctly

@ccnnde Yes, I am using expample.ovpn and I configure compatMode and useLegacyProvide but:
<img width="456" alt="Screen Shot 2022-04-25 at 00 24 46" src="https://user-images.githubusercontent.com/87758174/164988861-d3a5829c-5feb-4215-bb9e-bbb895af62f2.png">
r 
![Uploading Screen Shot 2022-04-25 at 07.20.08.png…]()
:

**Comment by ccnnde** [comment]
https://github.com/ccnnde/react-native-simple-openvpn/blob/e73019cd577bdd6e1cd9d8da9860286f602fb00c/example/App.js#L41

**Comment by nthiendev** [comment]
> https://github.com/ccnnde/react-native-simple-openvpn/blob/e73019cd577bdd6e1cd9d8da9860286f602fb00c/example/App.js#L41

@ccnnde Thank you very much <3<3
