### ISSUE TITLE
Please make custom file patch for security.

### ISSUE THREAD

**Issue by NgaChat** [ccnnde/react-native-simple-openvpn#21]
Please make custom file patch for server security.Cracker can crack assets folder with apk editer.and version 2 app crash when click connect button .

**Comment by ccnnde** [comment]
You can use `ovpnString` instead of specific configuration file.
> Please make custom file patch for server security.Cracker can crack assets folder with apk editer

You should create another issue and describe the reason for the crash
> and version 2 app crash when click connect button

**Comment by NgaChat** [comment]
> 
![Screen Shot 2022-04-25 at 8 10 41 AM](https://user-images.githubusercontent.com/31728118/165007191-503ee1df-f2ba-4068-a47b-bde8f700efb7.png)
How can i write for custom proxy in ovpnString?

**Comment by ccnnde** [comment]
Please see this commit https://github.com/ccnnde/react-native-simple-openvpn/commit/97492d246c0f400de52a57853f0fb45bf4054d75

You can install the latest version from github, or follow this commit to temporarily modify your files.

Then the following code should work:

```js
await RNSimpleOpenvpn.connect({
    remoteAddress: '',
    ovpnString: 'xxx',
    useCustomConfig: true,
    customConfigOptions: 'your custom proxy',
});
```

Let me know if it works.

**Comment by NgaChat** [comment]
> Please see this commit [97492d2](https://github.com/ccnnde/react-native-simple-openvpn/commit/97492d246c0f400de52a57853f0fb45bf4054d75)
> 
> You can install the latest version from github, or follow this commit to temporarily modify your files.
> 
> Then the following code should work:
> 
> ```js
> await RNSimpleOpenvpn.connect({
>     remoteAddress: '',
>     ovpnString: 'xxx',
>     useCustomConfig: true,
>     customConfigOptions: 'your custom proxy',
> });
> ```
> 
> Let me know if it works.

It is works ,Thanks
I have modify following mommit.
but ovpnString not work.

**Comment by ccnnde** [comment]
Do you mean custom config works when using config file? 

Using config file and ovpnString should have the same effect.

Can you debug your project with Android Studio? And Check here how the variable `cfg` differs when using the config file and ovpnString

https://github.com/ccnnde/react-native-simple-openvpn/blob/97492d246c0f400de52a57853f0fb45bf4054d75/vpnLib/src/main/java/de/blinkt/openvpn/VpnProfile.java#L722
