### ISSUE TITLE
Unable to resolve "react-native-simple-openvpn" from "App.js"

### ISSUE THREAD

**Issue by elmouddendotnet** [ccnnde/react-native-simple-openvpn#24]
i have installed & linked the package as mentioned in docs, got the jnilibs and put them in the right place. but i kept getting this error
**Unable to resolve "react-native-simple-openvpn" from "App.js"**

**Here is my App.js code:**

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import RNSimpleOpenvpn, { addVpnStateListener, removeVpnStateListener } from 'react-native-simple-openvpn';

export default function App() {

  async function startOvpn() {
    try {
      await RNSimpleOpenvpn.connect({
        remoteAddress: 'serverexample 80',
        ovpnFileName: 'client',
        username: 'username',
        password: 'password',
      });
    } catch (error) {
      // ...
    }
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>

      <TouchableOpacity style={{padding:100, backgroundColor:"#ffb800"}} onPress={startOvpn}>Click To Connect</TouchableOpacity>
      <StatusBar style="auto" />
    </View>
  );
}

**Comment by ccnnde** [comment]
What is your react native version? You can run the example to see if it works.

And you can try to initialize a new project and test again.
