### ISSUE TITLE
I can not find apple directory in my project

### ISSUE THREAD

**Issue by nthiendev** [ccnnde/react-native-simple-openvpn#26]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:latest
 - OS version: latest
 - react-native version:latest
 - react-native-simple-openvpn: version:latest
<img width="834" alt="Screen Shot 2022-06-07 at 12 54 38" src="https://user-images.githubusercontent.com/87758174/172306693-6e98f19c-5f12-4c67-94a2-9dc0788ef7de.png">

**Comment by nthiendev** [comment]
> **Bug description:**
> 
> **To Reproduce:**
> 
> **Expected behavior:**
> 
> **Screenshots/Videos:**
> 
> **Environment:**
> 
> * OS:latest
> * OS version: latest
> * react-native version:latest
> * react-native-simple-openvpn: version:latest
> 
> <img alt="Screen Shot 2022-06-07 at 12 54 38" width="834" src="https://user-images.githubusercontent.com/87758174/172306693-6e98f19c-5f12-4c67-94a2-9dc0788ef7de.png">

**Comment by m1guer** [comment]
you solved it?
