### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by ryzencool** [ccnnde/react-native-simple-openvpn#29]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/12694592/173212644-5eb59c38-fea0-45cd-87cb-e978c60bb709.png">

when I build on IOS, some failure happened
mac os version: monterey 12.4
xcode version: 13.4.1
react native version: 0.68.2
react natvie simple openvpn version: 2.0.0

**Comment by hkhawar21** [comment]
I am also facing the same issue when building for iOS after following their setup guide

**Comment by hkhawar21** [comment]
@ryzencool are you using expo for the app?

**Comment by OB-Mobile** [comment]
I am facing the same issue when trying to build for iOS, I am testing with a real device

**Comment by sandeeprana011** [comment]
> @ryzencool are you using expo for the app?

Yes, Same error and i am using Expo

**Comment by microinginer** [comment]
Some error

**Comment by Oleg12032002** [comment]
If an error occurred with the NetworkExtension imort.
You can try to replace the import
@import NetworkExtension
on
#import <NetworkExtension/NetworkExtension.h>

**Comment by omarsaade** [comment]
Replace your code with mine, and it will run correctly 
```
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
#import <NetworkExtension/NetworkExtension.h>
//@import NetworkExtension;

@interface RNSimpleOpenvpn : RCTEventEmitter <RCTBridgeModule>

@property(strong, nonatomic) NETunnelProviderManager *providerManager;

@property(strong, nonatomic) NSDictionary *ovpnOptions;

@property(strong, nonatomic) NSObject *vpnStateObserver;

+ (void)dispose;

@end
```
