### ISSUE TITLE
[Error: Prepare VPN failed]

### ISSUE THREAD

**Issue by pudrapembesi95** [ccnnde/react-native-simple-openvpn#4]
I ran the library on android platform but it gives error on ios platform

```
 RNSimpleOpenvpn.connect({
      remoteAddress: _MyAddress,
      ovpnFileName: _MyOvpnName,
      assetsPath: '',
      providerBundleIdentifier: "com.xxx.NEOvpn",
      localizedDescription: "_MyContainerTargetDisplayName",
    });
```
I followed the step by step ios guide
I get "Error: Prepare VPN failed" error when I use connect method as above
What do you think could be the reason?

**Environment:**
 OS version: 11.0
 "react-native": "0.66.2",
 "react-native-simple-openvpn": "^1.0.0"

**Comment by ccnnde** [comment]
Maybe there is something wrong with your iOS configuration. You can check the xcode log when you use the connect method

**Comment by yasirwahid** [comment]
Hey @ccnnde ,  Is there any remote vpn address for testing? and where would i get client.ovpn file? i need to use this library for andorid and ios and cant seem to find complete guidance of how to setup open vpn (remote address, ovpn file). any guidance would be helpful. 

Thanks

**Comment by ccnnde** [comment]
@yasirwahid You can take a look at the [Cake-VPN](https://github.com/ashraf789/Cake-VPN#note) project

**Comment by yasirwahid** [comment]
@ccnnde i have tried https://www.vpngate.net/en/ these server lists but it doesnt work. and they haven't showed how to generate your own .ovpn file so still no success.

**Comment by ccnnde** [comment]
@yasirwahid 

In fact, there is a column called **OpenVPN** in the middle of the VPN server list provided on the [VPN Gate](https://www.vpngate.net/en/) webpage, and you can see a link called **OpenVPN Config file**.

I wrote an [example](../blob/master/example/README.md) for reference only.

**Comment by yasirwahid** [comment]
@ccnnde Thanks, Really appreaciate it.
