### ISSUE TITLE
iOS build not connecting

### ISSUE THREAD

**Issue by ashavyrin** [ccnnde/react-native-simple-openvpn#40]
**Bug description:**
iOS build not connecting. Just shows 'The VPN is disconnected' . I followed the setup instructions as per the iOS guide.  Need advice on how to debug issue.

**Screenshots/Videos:**
![photo_2022-10-30 06 14 53](https://user-images.githubusercontent.com/18055671/198902133-6895af4d-3258-487a-b02c-104260d6b6d1.jpeg)

**Environment:**
 - OS: macOS Monterey
 - OS version: 12.6
 - react-native version:  0.70.0
 - react-native-simple-openvpn version: 2.0.0

**Comment by ccnnde** [comment]
In fact this situation is not easy to debug, can you connect to the VPN if you use the official OpenVPN app?

You can also use the OpenVPN configuration file provided with the example to test

**Comment by ashavyrin** [comment]
Yes I can connect with official app, and also on react native Android.

**Comment by iGroza** [comment]
same issue!

**Comment by tegozen** [comment]
i have this problem too

**Comment by senolatac** [comment]
me too

**Comment by nautikk** [comment]
any update on this

**Comment by ccnnde** [comment]
This method might solve the problem. https://github.com/ccnnde/react-native-simple-openvpn/issues/67#issuecomment-2345148660
