### ISSUE TITLE
Can not connect vpn on IOS device

### ISSUE THREAD

**Issue by nthiendev** [ccnnde/react-native-simple-openvpn#42]
**Bug description:**
<img width="787" alt="Screen Shot 2023-01-05 at 12 40 02" src="https://user-images.githubusercontent.com/87758174/210709921-c9c7e832-641e-464e-a9a9-85bc9dd6801c.png">
![IMG_0274](https://user-images.githubusercontent.com/87758174/210710056-80c10e44-9300-4d8b-9c90-247b0b80f744.PNG)
**To Reproduce:**

**Expected behavior:**
Can you help me to fix this issue
Thank you!

**Screenshots/Videos:**

**Environment:**
 - OS: mac
 - OS version: m1
 - react-native version: 0.70.6
 - react-native-simple-openvpn version: ^2.0.0

**Comment by ssmdssmp** [comment]
I am trying create VPN also, and I found that you cant create VPN app on iOS without Apple developer account with enterprise mode

**Comment by nthiendev** [comment]
> I am trying create VPN also, and I found that you cant create VPN app on iOS without Apple developer account with enterprise mode

😳

**Comment by ssmdssmp** [comment]
Btw, did you able to make it work on android?

**Comment by nthiendev** [comment]
> Btw, did you able to make it work on android?

Yes, on android it work ok.

**Comment by outZoNe** [comment]
Hi all. I seem to have the same problem for iOS:
<img width="390" alt="Снимок экрана 2023-01-09 в 01 04 23" src="https://user-images.githubusercontent.com/8308825/211221339-9c9c686d-a6ce-48bd-9245-2346222c2180.png">

However, on android everything works fine. Do you think it's because I don't have an apple developer account?

**Comment by ssmdssmp** [comment]
with it is also worked fine on android

**Comment by tegozen** [comment]
i have this problem too

**Comment by tegozen** [comment]
I don’t know why if I do it according to the ios guide it doesn’t work. i did so
![image](https://user-images.githubusercontent.com/29191360/215326168-1dfa41c9-69ba-42d7-a08d-e9e805f4f160.png)
at the same time, the library OpenVPNAdapter was added through "+" in the xcode
![image](https://user-images.githubusercontent.com/29191360/215326239-b5527c52-758c-45dd-9d76-25e6d2d6b458.png)
![image](https://user-images.githubusercontent.com/29191360/215326271-7a3758e6-6dc8-4ae0-b34e-c1217dac8902.png)
add package dependency
![image](https://user-images.githubusercontent.com/29191360/215326369-d07b637d-405e-4d20-88b2-19cc3058ed5e.png)
then select your project in "add to project"
then also add SystemConfiguration.framefork and UIKIT.framefork, but search just by name
then rebuild app

**Comment by nthiendev** [comment]
@ccnnde cc
is there any way you can help us? , please!

**Comment by ccnnde** [comment]
Sorry, I'm busy recently and don't have time

**Comment by w60083** [comment]
@nthiendev 
Hello, have you fixed that? What was the problem?

**Comment by SyedHaadi** [comment]
> Sorry, I'm busy recently and don't have time

Did you have time now And any solution for this ?

**Comment by ccnnde** [comment]
This method might solve the problem. [#67 (comment)](https://github.com/ccnnde/react-native-simple-openvpn/issues/67#issuecomment-2345148660)
