### ISSUE TITLE
Error: Error: Prepare VPN failed

### ISSUE THREAD

**Issue by iyyappanrock535** [ccnnde/react-native-simple-openvpn#43]
**Bug description:**
I have using React native ios tried but I got this issue.
await RNSimpleOpenvpn.connect({
          ovpnString: vpnConfigFile,
          providerBundleIdentifier:"com.baseserv.vpnapp",
        });

**Environment:**
 - OS: IOs
 - OS version: 15
 - react-native version:0.68.2
 - react-native-simple-openvpn version:^2.0.0

**Comment by liaostr** [comment]
Me too. Is there a solution

**Comment by w60083** [comment]
Its because the network extension doesn't work on ios simulator.
