### ISSUE TITLE
ReactNativeOpenvpn getting ios update required.

### ISSUE THREAD

**Issue by iyyappanrock535** [ccnnde/react-native-simple-openvpn#44]
**Bug description:**
ReactNativeOpenvpn getting ios update required.

**Screenshots/Videos:**
![IMG_F23A2F1CB2C0-1](https://user-images.githubusercontent.com/84359596/212127078-657771a7-6b8f-455f-bb3d-47b370f39338.jpeg)

**Comment by tegozen** [comment]
i have this problem too

**Comment by tegozen** [comment]
version, build and minimum deployments OS - package and extension must be the same - done

**Comment by ccnnde** [comment]
See [attention](https://github.com/ccnnde/react-native-simple-openvpn/blob/master/docs/iOS-Guide.md#attention)

> version, build and minimum deployments OS - package and extension must be the same - done
