### ISSUE TITLE
compatibility issue with newer react-native versions

### ISSUE THREAD

**Issue by Maders** [ccnnde/react-native-simple-openvpn#46]
**Bug description:**

I used the version `2.0.0` with clean install bare-minimum template of expo with react-native `0.71.3`, and I got Gradle build error related to in-compatibility between `kotlin-gradle-plugin:1.4.32` (was used in `vpnLib`) and `com.android.tools.build:gradle`.

The default `com.android.tools.build:gradle `dependencies in `android/gradle.build` for expo project:
```
dependencies {
        classpath('com.android.tools.build:gradle:7.4.1')
        classpath('com.facebook.react:react-native-gradle-plugin')
    }
```

The build error logs:
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':vpnLib' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

`./gradlew --version` output:
```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.18 (Azul Systems, Inc. 11.0.18+10-LTS)
OS:           Mac OS X 13.2.1 aarch64
```

**To Reproduce:**

1. initiate a clean and latest expo/react-native project
2. install `react-native-simple-openvpn`
3. try to build android

**Expected behavior:**

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/9904514/227232680-b4cdb243-cc8f-409f-9808-aef3e983b6d0.png)

**Environment:**
 - OS: `macOS`
 - OS version: `13.2.1`
 - react-native version: `0.71.3`
 - react-native-simple-openvpn version: `^2.0.0`

**Comment by ccnnde** [comment]
Thank you

**Comment by ccnnde** [comment]
Hello, I'm not sure if you are available. I would like to ask you a question, how do you use this module in expo? Recently, many people want to use it in expo, but it fails to run.
