### ISSUE TITLE
Inconsistency Between Local and Play Store Version of APK

### ISSUE THREAD

**Issue by AmirF194** [ccnnde/react-native-simple-openvpn#53]
I created an APK that works perfectly when installed directly on my phone. However, when I publish the same APK on Google Play, the app doesn't function properly. This issue only happens with the version downloaded from the Play Store. 
Any idea?

**Comment by ccnnde** [comment]
That's indeed quite strange. Perhaps you can add some logs to check each step.

**Comment by hm1061998** [comment]
@AmirF194 
I also met the same case. have you solved it yet?

**Comment by AmirF194** [comment]
No. I could not. 
I switched to another github repo.

**Comment by hm1061998** [comment]
@AmirF194 
i found the solution here, it is working for me
https://github.com/schwabe/ics-openvpn/issues/1331#issuecomment-885002947
