### ISSUE TITLE
when i click startOvpn then show { Cannot read property 'connect' of null} this error

### ISSUE THREAD

**Issue by shihabmilky1** [ccnnde/react-native-simple-openvpn#54]
![code](https://github.com/ccnnde/react-native-simple-openvpn/assets/76476417/993b4738-f761-443b-8f90-4b440415827e)
**this is my code** 

![Capture](https://github.com/ccnnde/react-native-simple-openvpn/assets/76476417/6865ba8d-001c-4faf-a16e-273c4b45b89b)
**and when click the button then show this error**

**please solve this immediately**

**Comment by ccnnde** [comment]
Are you using expo? This module is not compatible with expo

**Comment by master429** [comment]
> Are you using expo? This module is not compatible with expo你在使用世博会吗？此模块与 expo 不兼容

Can't this library be used in the expo project？

**Comment by ccnnde** [comment]
@master429 我没有特地对 expo 做过处理，但是可能可以。你看下这个，有人成功过，你可以问问看 
https://github.com/ccnnde/react-native-simple-openvpn/issues/57#issuecomment-1846430856
https://github.com/ccnnde/react-native-simple-openvpn/issues/46

**Comment by ccnnde** [comment]
https://github.com/ccnnde/react-native-simple-openvpn/issues/68#issuecomment-2446401034
