### ISSUE TITLE
Build fails on android 

### ISSUE THREAD

**Issue by Ozelea** [ccnnde/react-native-simple-openvpn#55]
**Bug description:**

`error Failed to install the app. Command failed with exit code 1: gradlew.bat tasks FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':tasks'. > Could not create task ':vpnLib:compileUiDebugAndroidTestKotlin'. > Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights.`

**To Reproduce:**

1. Create a new project
2. install react-native-simple-openvpn
3. make changes according to documentation in settings.gradle 
4. add jnilibs (I have added all of them)
5. run yarn android

**Expected behavior:**

Should build on android according to documentation

**Screenshots/Videos:**

**Environment:**
 - OS: Windows 11
 - react-native version: 0.72.0
 - react-native-simple-openvpn version: ^2.1.0

**Comment by mohamad-n** [comment]
Simple solution:

Open the file /node_modules/react-native-simple-openvpn/vpnLib/src/ui/java/de/blinkt/openvpn/fragments/Utils.kt and insert the following line on a new line after line number 93:

 
`else -> throw AssertionError()`

After that, rebuild the project.
