### ISSUE TITLE
Trying to connect showing null

### ISSUE THREAD

**Issue by mikias21** [ccnnde/react-native-simple-openvpn#57]
Hi there,

I'm trying to create a simple vpn client using expo, I tried my best to follow the instructions and run the example first but I'm getting **TypeError:  Cannot read property 'connect' of null** when i press the connect button. Can someone please tell me which part I'm doing wrong.

Steps I followed:
1. npx expo prebuild --clean
2. update the settings.gradle file to include 
include ':vpnLib'
project(':vpnLib').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-simple-openvpn/vpnLib')
3. include jinLibs to src/main/jinLibs
4. npx expo prebuild --clean
5. npx expo start
6. Scan and run the app on android

Please give me a hand I really need this

**Comment by ccnnde** [comment]
I haven't tested Expo myself, so I'm not sure if it's supported. However, there might be people who have tried it and succeeded. You can take a look at this issue https://github.com/ccnnde/react-native-simple-openvpn/issues/46  and consult with Maders for more information.

**Comment by ccnnde** [comment]
https://github.com/ccnnde/react-native-simple-openvpn/issues/68#issuecomment-2446401034
