### ISSUE TITLE
Error in Android app built with expo

### ISSUE THREAD

**Issue by master429** [ccnnde/react-native-simple-openvpn#58]
**Bug description:**
In the expo project, I used prebuild to generate the ios and android directories. I added the corresponding configuration in the android directory according to the documentation. When running yarn run android command, it gave me an error

**To Reproduce:**

**Expected behavior:**
Builds to android devices normally

**Screenshots/Videos:**
<img width="1129" alt="image" src="https://github.com/ccnnde/react-native-simple-openvpn/assets/76980858/f3217829-0151-4207-918d-9a7c9051627a">

**Environment:**
 - OS:MacOS
 - OS version:13.4
 - react-native version:0.72.6
 - react-native-simple-openvpn version:^2.1.0

**Comment by ccnnde** [comment]
@LynxSumit Give this a try and see if it works.

> If your project is based on [Expo](https://expo.io/), you need to eject your project by switching to the [Bare workflow](https://docs.expo.dev/workflow/customizing), in order to use this library.

**Comment by mohamad-n** [comment]
Simple solution:

Open the file /node_modules/react-native-simple-openvpn/vpnLib/src/ui/java/de/blinkt/openvpn/fragments/Utils.kt and insert the following line on a new line after line number 93:

 
`else -> throw AssertionError()`

After that, rebuild the project.

**Comment by ccnnde** [comment]
@mohamad-n thank you for your solution, would you be willing to submit a PR?

**Comment by mohamad-n** [comment]
> @mohamad-n thank you for your solution, would you be willing to submit a PR?

Certainly, if you're interested.

**Comment by ccnnde** [comment]
@mohamad-n Yes, I would like you to submit a PR. Thank you!

**Comment by mohamad-n** [comment]
> @mohamad-n Yes, I would like you to submit a PR. Thank you!

https://github.com/ccnnde/react-native-simple-openvpn/pull/61
