### ISSUE TITLE
Build does not go through TestFlight

### ISSUE THREAD

**Issue by KevinCHAILLY** [ccnnde/react-native-simple-openvpn#59]
Code is working as expected, unfortunately, when publishing the app for test, TestFlight returns an error "ERROR ITMS-90206: "Invalid Bundle. The bundle at '...' contains disallowed file 'Frameworks'."

Procedure was as follows : 
- pod install
- carthage update 
- code insertion, test build

And now publication does not work,

Thanks for the code !

**Comment by ccnnde** [comment]
I have tried to successfully publish to the App Store.

Maybe this issue caused it. [iOS-Guide.md#attention](/ccnnde/react-native-simple-openvpn/blob/master/docs/iOS-Guide.md#attention)

> The version and build of the container App should be consistent with the Network Extension, otherwise a warning will be generated when the app is uploaded to the App Store

**Comment by KevinCHAILLY** [comment]
Hi,

The problem was caused because the lines for carthage to copy framework were in the embeeded app and not the main,

Thanks for your times, and also many thanks for this good piece of software !
