### ISSUE TITLE
Read ovpn config failed: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by shoaib039** [ccnnde/react-native-simple-openvpn#6]
**I am getting this error Below**

**{
  "VPN_STATE_CONNECTED": 2,
  "VPN_OTHER_STATE": 4,
  "VPN_STATE_DISCONNECTED": 0,
  "VPN_STATE_CONNECTING": 1,
  "VPN_STATE_DISCONNECTING": 3
}
[Error: Read ovpn config failed: java.io.FileNotFoundException: android/app/src/main/assets/india-mumbai.ovpn]**

I setup my own Open Vpn Server, Configure file working on my Mobile as well as in PC, But its not working with this React-Native library. I configure well and same as given in desciption.  

**I print Error in Console**
![image](https://user-images.githubusercontent.com/95604832/152725901-514df355-306a-4a8e-bf22-5e95f4b624f3.png)

Please help me to solve this problem. Thank you

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.64.03
 - react-native-simple-openvpn version: 1.1.0

**Comment by ccnnde** [comment]
You don't need to pass the full path of the configuration file, `assetsPath` is empty or not passed.

See [assetsPath](../#assetspath) for details.

**Comment by shoaib039** [comment]
> You don't need to pass the full path of the configuration file, `assetsPath` is empty or not passed.
> 
> See [assetsPath](../#assetspath) for details.
My Code
![image](https://user-images.githubusercontent.com/95604832/153075862-00f564e8-b33b-4297-b94f-4e8eb7130ade.png)

Console Output
![image](https://user-images.githubusercontent.com/95604832/153075936-7d9f0daf-ba76-4c70-bd1f-a3378faee73e.png)

i modify code as you said, but VPN Not connecting to network giving this error

**Comment by ccnnde** [comment]
Please post the complete log in Android Studio

**Comment by ahammedmishal** [comment]
Hi got an error while connecting to VPN 
ERROR: Read Ovpn config failed jav.io.FileNotFoundException

![Screenshot_1670419468](https://user-images.githubusercontent.com/68768299/206191111-66401487-d77e-477c-bbcc-6801d49b673f.png)

**Comment by andbaish** [comment]
GG
