### ISSUE TITLE
TypeError: Cannot read property 'connect' of null

### ISSUE THREAD

**Issue by WANDIKAPRATAMA** [ccnnde/react-native-simple-openvpn#65]
Hi, can you give me a solution to the problem I am facing, currently when I try to connect with RNSimpleOpenvpn.connect I always get the error message [TypeError: Cannot read property 'connect' of null], without knowing what and from If the error message works, I really appreciate any reply you can give to help me solve this problem.

I think I have followed all the procedures attached to this documentation, I also used files from react-native-simple-openvpn/example
/App.js
 , in the context of the debugging process to compare the projects I created
![Screenshot 2024-06-13 165456](https://github.com/ccnnde/react-native-simple-openvpn/assets/159404291/872044d1-80f1-40f1-878d-da723cc38888)
![code](https://github.com/ccnnde/react-native-simple-openvpn/assets/159404291/45813244-b274-4cc4-bf5f-0faaa9ef62a9)

**Comment by ccnnde** [comment]
Please check this if you use Expo

https://github.com/ccnnde/react-native-simple-openvpn/issues/68#issuecomment-2446401034
