### ISSUE TITLE
How to use obfs4?

### ISSUE THREAD

**Issue by famdude** [ccnnde/react-native-simple-openvpn#66]
In some regions, the ISP or govrnment doesn't allow to use OpenVPN connection.

I want to use obfs4 to obfuscate traffic, so ISP or government won't be able to block OpenVPN traffic. How can I do so, using this project?

**Comment by ccnnde** [comment]
ics-openvpn does not seem to support obfs4. https://github.com/schwabe/ics-openvpn/issues/1339
