### ISSUE TITLE
VPN not connect in ios

### ISSUE THREAD

**Issue by Owaisdev0421** [ccnnde/react-native-simple-openvpn#67]
![SampleVPN](https://github.com/user-attachments/assets/60869a20-77aa-4e66-9312-a5b00607f6bf)
<img width="1440" alt="Screenshot 2024-09-04 at 2 24 02 PM" src="https://github.com/user-attachments/assets/ec1d68be-1094-49de-8770-06171f203085">
<img width="1440" alt="Screenshot 2024-09-04 at 2 24 37 PM" src="https://github.com/user-attachments/assets/73376aa5-bd5e-43f4-9c48-5526428bda49">
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: IOS
 - OS version: 17.6 mobile device
 - react-native version: 0.72.6
 - react-native-simple-openvpn version: ^2.1.0

**Comment by Owaisdev0421** [comment]
I configured all the libraries. OpenVPNAdapter. Also, set the complete profile. The Android side has been working perfectly. but I face issues is IOS. Plz give me a solution or any source file.

**Comment by ccnnde** [comment]
Can you provide a minimal code demo using a GitHub repository to reproduce the issue?

**Comment by Owaisdev0421** [comment]
I am working on a VPNDemo project hosted at [this GitHub repository](https://github.com/Owaisdev0421/VPNDemo.git). I need also assistance with rendering download and upload speed in the app when the notification is enabled. Currently, the speeds are shown in the notification, but I need to display the same data within the app interface as well.

Could you suggest the best way to synchronize this and ensure the speed metrics are updated in real-time in both the notification and the app?

**Comment by ccnnde** [comment]
Okay, I will take a look. As for the speed, it should require writing an interface to obtain it from the source code of ics-openvpn, but I currently don't have time to implement it.

**Comment by Owaisdev0421** [comment]
ok. can you plz check and resolve the **vpn connecting issue** on **IOS** side?

**Comment by ccnnde** [comment]
Please try setting the iOS version in the `Deployment info` of NEOvpn to the same value as in the container app, such as 12.4.
![image](https://github.com/user-attachments/assets/effa98c9-66ec-47c4-beb4-8ebaa03a0d6b)
![image](https://github.com/user-attachments/assets/da768350-f4ec-449e-86fa-c18e2d54642a)
