### ISSUE TITLE
android Build Failed with an exception

### ISSUE THREAD

**Issue by davenewton069** [ccnnde/react-native-simple-openvpn#68]
**Bug description:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: MacOS
 - OS version: '12.7.6"
 - react-native version: "0.72.10"
 - react-native-simple-openvpn version: "^2.1.1"

**Comment by ccnnde** [comment]
React Native v0.72.10 should use v2.1.2

**Comment by davenewton069** [comment]
So many bugs related 
Configure project :expo
Error: Autolinking is not set up in `settings.gradle`: expo modules won't be autolinked.

> Task :app:processDebugMainManifest
/Home/Clo/android/app/src/debug/AndroidManifest.xml:6:5-162 Warning:
        application@android:usesCleartextTraffic was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present

> Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Home/Clo/node_modules/@react-native-async-storage/async-storage/android/src/javaPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-fs:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-gesture-handler:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain


> Task :expo:compileDebugKotlin FAILED
e: file:///Home/Clo/node_modules/expo/android/src/main/java/expo/modules/ApplicationLifecycleDispatcher.kt:6:21 Unresolved reference: core
e: file:///Home/Clo/node_modules/expo/android/src/main/java/expo/modules/ApplicationLifecycleDispatcher.kt:9:31 Unresolved reference: ApplicationLifecycleListener
e: file:///Home/Clo/node_modules/expo/android/src/main/java/expo/modules/ApplicationLifecycleDispatcher.kt:12:66 Unresolved reference: ApplicationLifecycleListener

etc....

**Comment by davenewton069** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':expo-modules-core:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':expo-modules-core:debugCompileClasspath'.
   > Could not resolve com.facebook.fbjni:fbjni:0.5.1.
     Required by:
         project :expo-modules-core
      > Cannot find a version of 'com.facebook.fbjni:fbjni' that satisfies the version constraints:
           Dependency path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.fbjni:fbjni:0.5.1'
           Constraint path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.fbjni:fbjni:{strictly 0.3.0}' because of the following reason: debugRuntimeClasspath uses version 0.3.0
           Dependency path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.react:react-android:0.72.17' (debugVariantDefaultApiPublication) --> 'com.facebook.fbjni:fbjni:0.3.0'

   > Could not resolve com.facebook.fbjni:fbjni:{strictly 0.3.0}.
     Required by:
         project :expo-modules-core
      > Cannot find a version of 'com.facebook.fbjni:fbjni' that satisfies the version constraints:
           Dependency path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.fbjni:fbjni:0.5.1'
           Constraint path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.fbjni:fbjni:{strictly 0.3.0}' because of the following reason: debugRuntimeClasspath uses version 0.3.0
           Dependency path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.react:react-android:0.72.17' (debugVariantDefaultApiPublication) --> 'com.facebook.fbjni:fbjni:0.3.0'

   > Could not resolve com.facebook.fbjni:fbjni:0.3.0.
     Required by:
         project :expo-modules-core > com.facebook.react:react-android:0.72.17
      > Cannot find a version of 'com.facebook.fbjni:fbjni' that satisfies the version constraints:
           Dependency path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.fbjni:fbjni:0.5.1'
           Constraint path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.fbjni:fbjni:{strictly 0.3.0}' because of the following reason: debugRuntimeClasspath uses version 0.3.0
           Dependency path 'host.exp.exponent:expo-modules-core:1.12.26' --> 'com.facebook.react:react-android:0.72.17' (debugVariantDefaultApiPublication) --> 'com.facebook.fbjni:fbjni:0.3.0'

**Comment by ccnnde** [comment]
Sorry, this module has not been tested within the Expo framework.

**Comment by davenewton069** [comment]
> Sorry, this module has not been tested within the Expo framework.

Only for react-native cli then?

**Comment by ccnnde** [comment]
Probably, but there are also people who have used this module in Expo, and it seems to work.

**Comment by JeffreyZhu0201** [comment]
I had the same problem with react-native-cli 0.76

**Comment by davenewton069** [comment]
> Probably, but there are also people who have used this module in Expo, and it seems to work.

pls can you recommend an example

**Comment by davenewton069** [comment]
> I had the same problem with react-native-cli 0.76

How were you able to resolve the problem?

**Comment by ccnnde** [comment]
> > Probably, but there are also people who have used this module in Expo, and it seems to work.
> 
> pls can you recommend an example

It seems that someone who previously raised an issue has successfully used it in Expo, but there are currently no examples.

I will study how to use it in Expo recently.

**Comment by ccnnde** [comment]
I have successfully run the module in Expo.

You should create a development build **locally**, then just configure it according to the README.

https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build&buildEnv=local

> Any library that is compatible with React Native is compatible with the Expo project when you create a [**development build**](https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build&buildEnv=local). However, it may not be compatible with the [Expo Go](https://expo.dev/go) app

**Comment by davenewton069** [comment]
> https://docs.expo.dev/get-started/set-up-your-environment/?mode=development-build&buildEnv=local

and this works excellently well; you're able to connect and disconnect from Openvpn server using react-native-simple-openvpn?

**Comment by ccnnde** [comment]
yes

**Comment by davenewton069** [comment]
> yes

Ok thanks very much, I'll try it right away.. and if you have yours in a repository pls do well to share

**Comment by ccnnde** [comment]
Expo example https://github.com/ccnnde/rnovpn-expo-example

**Comment by davenewton069** [comment]
> Expo example https://github.com/ccnnde/rnovpn-expo-example

Finally, is it necessary to ascertain what java version is compatible? 

...
FAILURE: Build failed with an exception.

* Where:
Script 'rnovpn-expo-example-main/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 401

* What went wrong:
A problem occurred evaluating script.
> Process 'command 'node'' finished with non-zero exit value 1
...

**Comment by ccnnde** [comment]
Java17

**Comment by davenewton069** [comment]
> Java17

That's correct. Idk what then could be the issue.. 
I'm using node v18.17.0, and I have also tried updating react-native-community.
