### ISSUE TITLE
is it possible to use an ovpn remote file that will be downloaded first

### ISSUE THREAD

**Issue by khalisafkari** [ccnnde/react-native-simple-openvpn#7]
does the ovpn file have to be in the asset path

**Comment by ccnnde** [comment]
You can read the content of the file after downloading it and pass it as an [ovpnString](../#ovpnstring)

**Comment by Bimbimz** [comment]
i use ovpnString and got result

[Error: Load ovpn profile failed: android.os.RemoteException: You must select a User certificate]

**Comment by ayberkanilatsiz** [comment]
@Bimbimz i've have same issue. Did u find solution for it?

**Comment by khalisafkari** [comment]
@ayberkanilatsiz  remove all \n

**Comment by ayberkanilatsiz** [comment]
I read config like;

`const cert = await RNFS.readFile(destination, "utf8");

const config = {
        ovpnString: cert,
        username: user.email,
        password: user.pin,
        localizedDescription: 'LOCALIZED'
}

await RNSimpleOpenvpn.connect(config);`


Error: [Error: Load ovpn profile failed: android.os.RemoteException: You must select a User certificate]

**Comment by albae69** [comment]
@khalisafkari  how to pass the .ovpn config content as a string?
like this?
<img width="1440" alt="Screenshot 2023-08-04 at 13 52 43" src="https://github.com/ccnnde/react-native-simple-openvpn/assets/52565876/a99526a9-6465-46fc-abac-1860fc355a54">

**Comment by ccnnde** [comment]
@albae69 Yes, [ovpnstring](https://github.com/ccnnde/react-native-simple-openvpn/blob/master/docs/Reference.md#ovpnstring)
