### ISSUE TITLE
android 14 app crash issue

### ISSUE THREAD

**Issue by mandarinq3** [ccnnde/react-native-simple-openvpn#70]
app is crushing on android 14 

// erors that was in logcat when i tried to connect to server

Unable to start service de.blinkt.openvpn.core.OpenVPNService with Intent
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  targetSDK=34

**Comment by mandarinq3** [comment]
hi everyone, after long days of trying to fix this problem i finally manage to do it. i dont know what exactly helped (because i am not Java developer) but here is some modifications i have made . maybe it will help you save your time.
 so.... i went to this file =>
       node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java
and went to this method =>
      private void showNotification

1) i added this => @RequiresApi(api = Build.VERSION_CODES.Q) before private void showNotification ( i am not sure it is correct step)

2) i changed this=> Notification notification = nbuilder.getNotification();
into this=> Notification notification = nbuilder.build();
        
3) i changed this => startForeground(notificationId, notification);
into this => if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                      startForeground(notificationId, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC);
                      return;
                   } else {
                      startForeground(notificationId, notification);  // for old android versions
                   }

then i went to this file =>node_modules\react-native-simple-openvpn\android\src\main\AndroidManifest.xml

1)  i changed this => <service
            android:name="de.blinkt.openvpn.core.OpenVPNService"
            android:exported="false"
            android:permission="android.permission.BIND_VPN_SERVICE">
into this =>  <service
            android:name="de.blinkt.openvpn.core.OpenVPNService"
            android:exported="false"
            android:permission="android.permission.BIND_VPN_SERVICE"
            android:foregroundServiceType="dataSync"
            >
2) and also added this <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC"/>

i think this is all i did to make it work. maybe i have forgotten something, or maybe i did some unnessary changes. as i mentiond earlier i am not java developer ))) good luck everyone.

**Comment by ccnnde** [comment]
Thank you for the solutions you provided.

Was the modification to `AndroidManifest.xml` overlooked?

> then i went to this file =>node_modules\react-native-simple-openvpn\android\src\main\AndroidManifest.xml
>
> i changed this => ?
>
> into this => ?
>
> and also added this ?

**Comment by ccnnde** [comment]
https://github.com/ccnnde/react-native-simple-openvpn/issues/69

**Comment by mandarinq3** [comment]
comment was edited with adding overlooked information.

**Comment by ccnnde** [comment]
After testing, you only need to modify the `AndroidManifest.xml`.

v2.1.3 has already fixed the issue.
