### ISSUE TITLE
Question: How can I contact you?

### ISSUE THREAD

**Issue by DaviDecoder** [ccnnde/react-native-simple-openvpn#72]
Hello,
I've tried contacting you via email but I have not heard a response, is there a live chat platform I can ask you some questions?
Thanks.

**Comment by ccnnde** [comment]
You can ask any questions directly here

**Comment by DaviDecoder** [comment]
@ccnnde  It is a private question that I want to directly ask. How can I get in contact with you?

**Comment by ccnnde** [comment]
You can use your usual contact methods.

**Comment by DaviDecoder** [comment]
"Such as? You have no forms of contact methods listed anywhere." and don't respond on the email or look at the emails

**Comment by DaviDecoder** [comment]
If you don't mind you can contact me on discord a.thegreat, we would like to work with you. My company is whynotprivacy a privacy oriented company and we need your help with the vpn.

**Comment by ccnnde** [comment]
Thank you for the invitation, but I don't actually know much about VPNs.

**Comment by DaviDecoder** [comment]
You made the VPN backend that we are using currently and its not functioning well things like kill switch and always on are not really working.
