### ISSUE TITLE
Connect On Demand

### ISSUE THREAD

**Issue by DaviDecoder** [ccnnde/react-native-simple-openvpn#73]
Hello,
I am wondering how to enable Connect On Demand slider for iOS platform with this specific plugin.
Thank you.

**Comment by ccnnde** [comment]
I don't quite understand what "Connect On Demand slider for iOS platform" means.

**Comment by DaviDecoder** [comment]
By "Connect On Demand slider for iOS," I'm referring to the feature that allows the VPN to automatically establish a connection when needed, without requiring the user to manually toggle the VPN on or off. This functionality is typically controlled by a setting or slider within the IOS VPN configuration.

Could you please guide me on how to enable this feature within the plugin for iOS? It would greatly improve the user experience, and I’d appreciate your help in making it work.

Thank you for your time and assistance!

**Example SurfShark VPN Configuration OPENVPN**
<img width="359" alt="Screenshot 2024-11-11 at 02 53 35" src="https://github.com/user-attachments/assets/640b384e-d199-486a-a59b-7ea0bb17a4ef">

**Comment by DaviDecoder** [comment]
Any update @ccnnde ?

**Comment by ccnnde** [comment]
I’ve been quite busy lately; you can try checking out these links.

https://github.com/ss-abramchuk/OpenVPNAdapter/issues/168

https://developer.apple.com/documentation/networkextension/neondemandruleconnect

**Comment by DaviDecoder** [comment]
![image](https://github.com/user-attachments/assets/f77d9608-54a0-4985-a6e5-d491e3aad5fd)

@ccnnde
