### ISSUE TITLE
Payment for Improving react-native-simple-openvpn Repo

### ISSUE THREAD

**Issue by DaviDecoder** [ccnnde/react-native-simple-openvpn#76]
Hey @ccnde,
I’d like to make a $500 payment to improve the react-native-simple-openvpn repo and fix some issues I’ve been running into

Do you have a Telegram or Discord so we can discuss the details and I can show you the issues directly?

**Comment by ccnnde** [comment]
I registered on Discord, and my username is `norcod_`

**Comment by DaviDecoder** [comment]
I sent a friend request, did you receive it? 
My discord handle is @richi0808

**Comment by Luthamm** [comment]
@DaviDecoder Hey there. I have been working with this repo trying to get a VPN app working on iOS, however, I'm running into issues.

When connecting to my server it gets stuck on "connecting" in the iOS settings. If you are willing to share- do you know how to get over this hump and actually connected to the server? Any advice would be greatly appreciated.

**Comment by DaviDecoder** [comment]
@ccnnde open your Discord

**Comment by DaviDecoder** [comment]
@Luthamm 
I don't know man sorry
