### ISSUE TITLE
How to configure allowed apps using the package name/bundle id?

### ISSUE THREAD

**Issue by vinaydrevankar** [ccnnde/react-native-simple-openvpn#9]
How to configure allowed apps using the package name/bundle id?

**Comment by ccnnde** [comment]
What exactly do you mean? providerBundleIdentifier?

**Comment by vinaydrevankar** [comment]
Android ics-openvpn we can mention the apps(packagename) that we dont want to access the vpn connection. instead those apps access the normal internet connection.

I could see this also in your library in file VpnProfile.java. However its not exposed in react native

mAllowedAppsVpnAreDisallowed - if set true, the packages that we specify setAllowedVpnPackages use normal internet connecton. If false, the packages that we specify setAllowedVpnPackages use our VPN connection

**Comment by ccnnde** [comment]
I see, I'll look into it when I'm free.
